#ifndef _CONFIG_H_
#define _CONFIG_H_

#define MAX_PLAYERS 1024
#define MAX_FRUITS 1024

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720
#define BORDER_SIZE 10

#define GRID_SIZE 20

#define MAP_SIZE (SCREEN_HEIGHT - BORDER_SIZE * 2)
#define OBJECTS_SIZE (MAP_SIZE / GRID_SIZE)

#endif
